export const REDIS_KEY_NETWORK: string = 'network'
export const REDIS_KEY_NETWORKS: string = 'networks'
export const REDIS_KEY_CITIES: string = 'cities'
export const REDIS_KEY_CINEMAS: string = 'cinemas'
export const REDIS_KEY_CINEMA: string = 'cinema'
export const REDIS_KEY_MOVIES: string = 'movies'
export const REDIS_KEY_MOVIE: string = 'movie'
export const REDIS_KEY_SHOWTIMES: string = 'showtimes'